# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# Fixed import path for package-relative import
from . import sandbox_pb2 as sandbox_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sandbox/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """SandboxService handles file operations in WASI-isolated workspaces.
    All paths are relative to the session's workspace root.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileRead = channel.unary_unary(
                '/shannon.sandbox.SandboxService/FileRead',
                request_serializer=sandbox_dot_sandbox__pb2.FileReadRequest.SerializeToString,
                response_deserializer=sandbox_dot_sandbox__pb2.FileReadResponse.FromString,
                _registered_method=True)
        self.FileWrite = channel.unary_unary(
                '/shannon.sandbox.SandboxService/FileWrite',
                request_serializer=sandbox_dot_sandbox__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=sandbox_dot_sandbox__pb2.FileWriteResponse.FromString,
                _registered_method=True)
        self.FileList = channel.unary_unary(
                '/shannon.sandbox.SandboxService/FileList',
                request_serializer=sandbox_dot_sandbox__pb2.FileListRequest.SerializeToString,
                response_deserializer=sandbox_dot_sandbox__pb2.FileListResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/shannon.sandbox.SandboxService/ExecuteCommand',
                request_serializer=sandbox_dot_sandbox__pb2.CommandRequest.SerializeToString,
                response_deserializer=sandbox_dot_sandbox__pb2.CommandResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """SandboxService handles file operations in WASI-isolated workspaces.
    All paths are relative to the session's workspace root.
    """

    def FileRead(self, request, context):
        """Read a file from session workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWrite(self, request, context):
        """Write a file to session workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """List files in session workspace directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute a safe command in session workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileRead': grpc.unary_unary_rpc_method_handler(
                    servicer.FileRead,
                    request_deserializer=sandbox_dot_sandbox__pb2.FileReadRequest.FromString,
                    response_serializer=sandbox_dot_sandbox__pb2.FileReadResponse.SerializeToString,
            ),
            'FileWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.FileWrite,
                    request_deserializer=sandbox_dot_sandbox__pb2.FileWriteRequest.FromString,
                    response_serializer=sandbox_dot_sandbox__pb2.FileWriteResponse.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=sandbox_dot_sandbox__pb2.FileListRequest.FromString,
                    response_serializer=sandbox_dot_sandbox__pb2.FileListResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=sandbox_dot_sandbox__pb2.CommandRequest.FromString,
                    response_serializer=sandbox_dot_sandbox__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shannon.sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shannon.sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """SandboxService handles file operations in WASI-isolated workspaces.
    All paths are relative to the session's workspace root.
    """

    @staticmethod
    def FileRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.sandbox.SandboxService/FileRead',
            sandbox_dot_sandbox__pb2.FileReadRequest.SerializeToString,
            sandbox_dot_sandbox__pb2.FileReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.sandbox.SandboxService/FileWrite',
            sandbox_dot_sandbox__pb2.FileWriteRequest.SerializeToString,
            sandbox_dot_sandbox__pb2.FileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.sandbox.SandboxService/FileList',
            sandbox_dot_sandbox__pb2.FileListRequest.SerializeToString,
            sandbox_dot_sandbox__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.sandbox.SandboxService/ExecuteCommand',
            sandbox_dot_sandbox__pb2.CommandRequest.SerializeToString,
            sandbox_dot_sandbox__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
