# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent import agent_pb2 as agent_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/shannon.agent.AgentService/ExecuteTask',
                request_serializer=agent_dot_agent__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)
        self.StreamExecuteTask = channel.unary_stream(
                '/shannon.agent.AgentService/StreamExecuteTask',
                request_serializer=agent_dot_agent__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.TaskUpdate.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/shannon.agent.AgentService/GetCapabilities',
                request_serializer=agent_dot_agent__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/shannon.agent.AgentService/HealthCheck',
                request_serializer=agent_dot_agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.DiscoverTools = channel.unary_unary(
                '/shannon.agent.AgentService/DiscoverTools',
                request_serializer=agent_dot_agent__pb2.DiscoverToolsRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.DiscoverToolsResponse.FromString,
                _registered_method=True)
        self.GetToolCapability = channel.unary_unary(
                '/shannon.agent.AgentService/GetToolCapability',
                request_serializer=agent_dot_agent__pb2.GetToolCapabilityRequest.SerializeToString,
                response_deserializer=agent_dot_agent__pb2.GetToolCapabilityResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent_dot_agent__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.ExecuteTaskResponse.SerializeToString,
            ),
            'StreamExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExecuteTask,
                    request_deserializer=agent_dot_agent__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.TaskUpdate.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=agent_dot_agent__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent_dot_agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'DiscoverTools': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverTools,
                    request_deserializer=agent_dot_agent__pb2.DiscoverToolsRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.DiscoverToolsResponse.SerializeToString,
            ),
            'GetToolCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolCapability,
                    request_deserializer=agent_dot_agent__pb2.GetToolCapabilityRequest.FromString,
                    response_serializer=agent_dot_agent__pb2.GetToolCapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shannon.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shannon.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.agent.AgentService/ExecuteTask',
            agent_dot_agent__pb2.ExecuteTaskRequest.SerializeToString,
            agent_dot_agent__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shannon.agent.AgentService/StreamExecuteTask',
            agent_dot_agent__pb2.ExecuteTaskRequest.SerializeToString,
            agent_dot_agent__pb2.TaskUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.agent.AgentService/GetCapabilities',
            agent_dot_agent__pb2.GetCapabilitiesRequest.SerializeToString,
            agent_dot_agent__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.agent.AgentService/HealthCheck',
            agent_dot_agent__pb2.HealthCheckRequest.SerializeToString,
            agent_dot_agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.agent.AgentService/DiscoverTools',
            agent_dot_agent__pb2.DiscoverToolsRequest.SerializeToString,
            agent_dot_agent__pb2.DiscoverToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.agent.AgentService/GetToolCapability',
            agent_dot_agent__pb2.GetToolCapabilityRequest.SerializeToString,
            agent_dot_agent__pb2.GetToolCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
