# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from orchestrator import orchestrator_pb2 as orchestrator_dot_orchestrator__pb2


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/SubmitTask',
                request_serializer=orchestrator_dot_orchestrator__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/GetTaskStatus',
                request_serializer=orchestrator_dot_orchestrator__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.GetTaskStatusResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/CancelTask',
                request_serializer=orchestrator_dot_orchestrator__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ListTasks',
                request_serializer=orchestrator_dot_orchestrator__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.GetSessionContext = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/GetSessionContext',
                request_serializer=orchestrator_dot_orchestrator__pb2.GetSessionContextRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.GetSessionContextResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ListTemplates',
                request_serializer=orchestrator_dot_orchestrator__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.ApproveTask = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ApproveTask',
                request_serializer=orchestrator_dot_orchestrator__pb2.ApproveTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ApproveTaskResponse.FromString,
                _registered_method=True)
        self.GetPendingApprovals = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/GetPendingApprovals',
                request_serializer=orchestrator_dot_orchestrator__pb2.GetPendingApprovalsRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.GetPendingApprovalsResponse.FromString,
                _registered_method=True)
        self.PauseTask = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/PauseTask',
                request_serializer=orchestrator_dot_orchestrator__pb2.PauseTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.PauseTaskResponse.FromString,
                _registered_method=True)
        self.ResumeTask = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ResumeTask',
                request_serializer=orchestrator_dot_orchestrator__pb2.ResumeTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ResumeTaskResponse.FromString,
                _registered_method=True)
        self.GetControlState = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/GetControlState',
                request_serializer=orchestrator_dot_orchestrator__pb2.GetControlStateRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.GetControlStateResponse.FromString,
                _registered_method=True)
        self.SubmitReviewDecision = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/SubmitReviewDecision',
                request_serializer=orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionResponse.FromString,
                _registered_method=True)
        self.RecordTokenUsage = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/RecordTokenUsage',
                request_serializer=orchestrator_dot_orchestrator__pb2.RecordTokenUsageRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.RecordTokenUsageResponse.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/CreateSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/GetSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.GetScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ListSchedules',
                request_serializer=orchestrator_dot_orchestrator__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/UpdateSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.UpdateScheduleResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/DeleteSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.PauseSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/PauseSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.PauseScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.PauseScheduleResponse.FromString,
                _registered_method=True)
        self.ResumeSchedule = channel.unary_unary(
                '/shannon.orchestrator.OrchestratorService/ResumeSchedule',
                request_serializer=orchestrator_dot_orchestrator__pb2.ResumeScheduleRequest.SerializeToString,
                response_deserializer=orchestrator_dot_orchestrator__pb2.ResumeScheduleResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Template catalog
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveTask(self, request, context):
        """Human intervention endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingApprovals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTask(self, request, context):
        """Workflow control (pause/resume/cancel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitReviewDecision(self, request, context):
        """HITL Research Review
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTokenUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Schedule management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.SubmitTaskRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.GetTaskStatusResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.CancelTaskRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.CancelTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ListTasksRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetSessionContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionContext,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.GetSessionContextRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.GetSessionContextResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ListTemplatesRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'ApproveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveTask,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ApproveTaskRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ApproveTaskResponse.SerializeToString,
            ),
            'GetPendingApprovals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingApprovals,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.GetPendingApprovalsRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.GetPendingApprovalsResponse.SerializeToString,
            ),
            'PauseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTask,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.PauseTaskRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.PauseTaskResponse.SerializeToString,
            ),
            'ResumeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTask,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ResumeTaskRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ResumeTaskResponse.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.GetControlStateRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.GetControlStateResponse.SerializeToString,
            ),
            'SubmitReviewDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReviewDecision,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionResponse.SerializeToString,
            ),
            'RecordTokenUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTokenUsage,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.RecordTokenUsageRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.RecordTokenUsageResponse.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.CreateScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.GetScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.GetScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ListSchedulesRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ListSchedulesResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.UpdateScheduleResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'PauseSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.PauseScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.PauseScheduleResponse.SerializeToString,
            ),
            'ResumeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSchedule,
                    request_deserializer=orchestrator_dot_orchestrator__pb2.ResumeScheduleRequest.FromString,
                    response_serializer=orchestrator_dot_orchestrator__pb2.ResumeScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shannon.orchestrator.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shannon.orchestrator.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/SubmitTask',
            orchestrator_dot_orchestrator__pb2.SubmitTaskRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/GetTaskStatus',
            orchestrator_dot_orchestrator__pb2.GetTaskStatusRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.GetTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/CancelTask',
            orchestrator_dot_orchestrator__pb2.CancelTaskRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ListTasks',
            orchestrator_dot_orchestrator__pb2.ListTasksRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/GetSessionContext',
            orchestrator_dot_orchestrator__pb2.GetSessionContextRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.GetSessionContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ListTemplates',
            orchestrator_dot_orchestrator__pb2.ListTemplatesRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ApproveTask',
            orchestrator_dot_orchestrator__pb2.ApproveTaskRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ApproveTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/GetPendingApprovals',
            orchestrator_dot_orchestrator__pb2.GetPendingApprovalsRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.GetPendingApprovalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/PauseTask',
            orchestrator_dot_orchestrator__pb2.PauseTaskRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.PauseTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ResumeTask',
            orchestrator_dot_orchestrator__pb2.ResumeTaskRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ResumeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/GetControlState',
            orchestrator_dot_orchestrator__pb2.GetControlStateRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.GetControlStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitReviewDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/SubmitReviewDecision',
            orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.SubmitReviewDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTokenUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/RecordTokenUsage',
            orchestrator_dot_orchestrator__pb2.RecordTokenUsageRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.RecordTokenUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/CreateSchedule',
            orchestrator_dot_orchestrator__pb2.CreateScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/GetSchedule',
            orchestrator_dot_orchestrator__pb2.GetScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ListSchedules',
            orchestrator_dot_orchestrator__pb2.ListSchedulesRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/UpdateSchedule',
            orchestrator_dot_orchestrator__pb2.UpdateScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.UpdateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/DeleteSchedule',
            orchestrator_dot_orchestrator__pb2.DeleteScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/PauseSchedule',
            orchestrator_dot_orchestrator__pb2.PauseScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.PauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.orchestrator.OrchestratorService/ResumeSchedule',
            orchestrator_dot_orchestrator__pb2.ResumeScheduleRequest.SerializeToString,
            orchestrator_dot_orchestrator__pb2.ResumeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
