# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from orchestrator import streaming_pb2 as orchestrator_dot_streaming__pb2


class StreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTaskExecution = channel.unary_stream(
                '/shannon.orchestrator.StreamingService/StreamTaskExecution',
                request_serializer=orchestrator_dot_streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=orchestrator_dot_streaming__pb2.TaskUpdate.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTaskExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTaskExecution': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskExecution,
                    request_deserializer=orchestrator_dot_streaming__pb2.StreamRequest.FromString,
                    response_serializer=orchestrator_dot_streaming__pb2.TaskUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shannon.orchestrator.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shannon.orchestrator.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTaskExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shannon.orchestrator.StreamingService/StreamTaskExecution',
            orchestrator_dot_streaming__pb2.StreamRequest.SerializeToString,
            orchestrator_dot_streaming__pb2.TaskUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
