# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator/streaming.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'orchestrator/streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1corchestrator/streaming.proto\x12\x14shannon.orchestrator\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n\rStreamRequest\x12\x1f\n\x0bworkflow_id\x18\x01 \x01(\tR\nworkflowId\x12\x14\n\x05types\x18\x02 \x03(\tR\x05types\x12\"\n\rlast_event_id\x18\x03 \x01(\x04R\x0blastEventId\x12$\n\x0elast_stream_id\x18\x04 \x01(\tR\x0clastStreamId\"\xdf\x01\n\nTaskUpdate\x12\x1f\n\x0bworkflow_id\x18\x01 \x01(\tR\nworkflowId\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n\x08\x61gent_id\x18\x03 \x01(\tR\x07\x61gentId\x12\x18\n\x07message\x18\x04 \x01(\tR\x07message\x12\x38\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n\x03seq\x18\x06 \x01(\x04R\x03seq\x12\x1b\n\tstream_id\x18\x07 \x01(\tR\x08streamId2r\n\x10StreamingService\x12^\n\x13StreamTaskExecution\x12#.shannon.orchestrator.StreamRequest\x1a .shannon.orchestrator.TaskUpdate0\x01\x42HZFgithub.com/Kocoro-lab/Shannon/go/orchestrator/internal/pb/orchestratorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator.streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/Kocoro-lab/Shannon/go/orchestrator/internal/pb/orchestrator'
  _globals['_STREAMREQUEST']._serialized_start=88
  _globals['_STREAMREQUEST']._serialized_end=232
  _globals['_TASKUPDATE']._serialized_start=235
  _globals['_TASKUPDATE']._serialized_end=458
  _globals['_STREAMINGSERVICE']._serialized_start=460
  _globals['_STREAMINGSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
