//! Generated protobuf definitions.
//!
//! This module contains the Rust code generated from Shannon's protobuf
//! definitions. The code is generated by tonic-build in build.rs.

// The actual generated files are included via include! in grpc_client.rs
// This module exists for organizational purposes.

// Re-export from grpc_client for convenience
pub use crate::gateway::grpc_client::proto::*;
