// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskDecomposition {
    #[prost(enumeration = "super::common::ExecutionMode", tag = "1")]
    pub mode: i32,
    #[prost(double, tag = "2")]
    pub complexity_score: f64,
    #[prost(message, repeated, tag = "3")]
    pub agent_tasks: ::prost::alloc::vec::Vec<AgentTask>,
    #[prost(message, optional, tag = "4")]
    pub dag: ::core::option::Option<DagStructure>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentTask {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub dependencies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub input: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, repeated, tag = "6")]
    pub required_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "super::common::ModelTier", tag = "7")]
    pub model_tier: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DagStructure {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<DagNode>,
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<DagEdge>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DagNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_task_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub level: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DagEdge {
    #[prost(string, tag = "1")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitTaskRequest {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<super::common::TaskMetadata>,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub context: ::core::option::Option<::prost_types::Struct>,
    #[prost(bool, tag = "4")]
    pub auto_decompose: bool,
    #[prost(message, optional, tag = "5")]
    pub manual_decomposition: ::core::option::Option<TaskDecomposition>,
    /// Session continuity support
    #[prost(message, optional, tag = "6")]
    pub session_context: ::core::option::Option<SessionContext>,
    /// Require human approval before executing
    #[prost(bool, tag = "10")]
    pub require_approval: bool,
}
/// Session context for multi-turn conversations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionContext {
    /// Recent conversation history
    #[prost(message, repeated, tag = "1")]
    pub history: ::prost::alloc::vec::Vec<ConversationMessage>,
    /// Persistent session data
    #[prost(message, optional, tag = "2")]
    pub persistent_context: ::core::option::Option<::prost_types::Struct>,
    /// Files created in this session
    #[prost(string, repeated, tag = "3")]
    pub files_created: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Tools used in this session
    #[prost(string, repeated, tag = "4")]
    pub tools_used: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Accumulated token usage
    #[prost(int32, tag = "5")]
    pub total_tokens_used: i32,
    /// Accumulated cost
    #[prost(double, tag = "6")]
    pub total_cost_usd: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationMessage {
    /// "user", "assistant", "system"
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "4")]
    pub tokens_used: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitTaskResponse {
    #[prost(string, tag = "1")]
    pub workflow_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::StatusCode", tag = "3")]
    pub status: i32,
    #[prost(message, optional, tag = "4")]
    pub decomposition: ::core::option::Option<TaskDecomposition>,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTaskStatusRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_details: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTaskStatusResponse {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "2")]
    pub status: i32,
    #[prost(double, tag = "3")]
    pub progress: f64,
    #[prost(string, tag = "4")]
    pub result: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub metrics: ::core::option::Option<super::common::ExecutionMetrics>,
    #[prost(message, repeated, tag = "6")]
    pub agent_statuses: ::prost::alloc::vec::Vec<AgentTaskStatus>,
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentTaskStatus {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub result: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub token_usage: ::core::option::Option<super::common::TokenUsage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelTaskRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelTaskResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTasksRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    #[prost(int32, tag = "4")]
    pub offset: i32,
    #[prost(enumeration = "TaskStatus", tag = "5")]
    pub filter_status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTasksResponse {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<TaskSummary>,
    #[prost(int32, tag = "2")]
    pub total_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskSummary {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "3")]
    pub status: i32,
    #[prost(enumeration = "super::common::ExecutionMode", tag = "4")]
    pub mode: i32,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub completed_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub total_token_usage: ::core::option::Option<super::common::TokenUsage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionContextRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionContextResponse {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub context: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, repeated, tag = "3")]
    pub recent_tasks: ::prost::alloc::vec::Vec<TaskSummary>,
    #[prost(message, optional, tag = "4")]
    pub session_token_usage: ::core::option::Option<super::common::TokenUsage>,
}
/// Template catalog messages
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TemplateSummary {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content_hash: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTemplatesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTemplatesResponse {
    #[prost(message, repeated, tag = "1")]
    pub templates: ::prost::alloc::vec::Vec<TemplateSummary>,
}
/// Human intervention messages
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApproveTaskRequest {
    #[prost(string, tag = "1")]
    pub approval_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub workflow_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub approved: bool,
    #[prost(string, tag = "5")]
    pub feedback: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub modified_action: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub approved_by: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApproveTaskResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPendingApprovalsRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPendingApprovalsResponse {
    #[prost(message, repeated, tag = "1")]
    pub approvals: ::prost::alloc::vec::Vec<PendingApproval>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PendingApproval {
    #[prost(string, tag = "1")]
    pub approval_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub workflow_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub proposed_action: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub requested_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub metadata: ::core::option::Option<::prost_types::Struct>,
}
/// Workflow control messages
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseTaskRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseTaskResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeTaskRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeTaskResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetControlStateRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetControlStateResponse {
    #[prost(bool, tag = "1")]
    pub is_paused: bool,
    #[prost(bool, tag = "2")]
    pub is_cancelled: bool,
    /// RFC3339 timestamp, empty if never paused
    #[prost(string, tag = "3")]
    pub paused_at: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub pause_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub paused_by: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub cancel_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub cancelled_by: ::prost::alloc::string::String,
}
/// Schedule management messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateScheduleRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cron_expression: ::prost::alloc::string::String,
    /// Default: UTC
    #[prost(string, tag = "4")]
    pub timezone: ::prost::alloc::string::String,
    /// Task template
    #[prost(string, tag = "5")]
    pub task_query: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub task_context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Resource limits
    #[prost(double, tag = "7")]
    pub max_budget_per_run_usd: f64,
    #[prost(int32, tag = "8")]
    pub timeout_seconds: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateScheduleResponse {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// RFC3339
    #[prost(string, tag = "3")]
    pub next_run_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetScheduleRequest {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleInfo {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub cron_expression: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub timezone: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub task_query: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "7")]
    pub task_context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(double, tag = "8")]
    pub max_budget_per_run_usd: f64,
    #[prost(int32, tag = "9")]
    pub timeout_seconds: i32,
    /// ACTIVE, PAUSED, DELETED
    #[prost(string, tag = "10")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub last_run_at: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub next_run_at: ::prost::alloc::string::String,
    #[prost(int32, tag = "15")]
    pub total_runs: i32,
    #[prost(int32, tag = "16")]
    pub successful_runs: i32,
    #[prost(int32, tag = "17")]
    pub failed_runs: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleResponse {
    #[prost(message, optional, tag = "1")]
    pub schedule: ::core::option::Option<ScheduleInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSchedulesRequest {
    /// Default: 50, max: 100
    #[prost(int32, tag = "1")]
    pub page_size: i32,
    /// Default: 1
    #[prost(int32, tag = "2")]
    pub page: i32,
    /// Filter: ACTIVE, PAUSED, ALL
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSchedulesResponse {
    #[prost(message, repeated, tag = "1")]
    pub schedules: ::prost::alloc::vec::Vec<ScheduleInfo>,
    #[prost(int32, tag = "2")]
    pub total_count: i32,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateScheduleRequest {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    /// Optional fields (only update if set)
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub cron_expression: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub task_query: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "7")]
    pub task_context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(double, optional, tag = "8")]
    pub max_budget_per_run_usd: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "9")]
    pub timeout_seconds: ::core::option::Option<i32>,
    /// Set to true to explicitly clear task_context (empty map is indistinguishable from not set)
    #[prost(bool, tag = "10")]
    pub clear_task_context: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateScheduleResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub next_run_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteScheduleRequest {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteScheduleResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseScheduleRequest {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseScheduleResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeScheduleRequest {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeScheduleResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub next_run_at: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskStatus {
    Unspecified = 0,
    Queued = 1,
    Running = 2,
    Completed = 3,
    Failed = 4,
    Cancelled = 5,
    Timeout = 6,
    Paused = 7,
}
impl TaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TASK_STATUS_UNSPECIFIED",
            Self::Queued => "TASK_STATUS_QUEUED",
            Self::Running => "TASK_STATUS_RUNNING",
            Self::Completed => "TASK_STATUS_COMPLETED",
            Self::Failed => "TASK_STATUS_FAILED",
            Self::Cancelled => "TASK_STATUS_CANCELLED",
            Self::Timeout => "TASK_STATUS_TIMEOUT",
            Self::Paused => "TASK_STATUS_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TASK_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "TASK_STATUS_QUEUED" => Some(Self::Queued),
            "TASK_STATUS_RUNNING" => Some(Self::Running),
            "TASK_STATUS_COMPLETED" => Some(Self::Completed),
            "TASK_STATUS_FAILED" => Some(Self::Failed),
            "TASK_STATUS_CANCELLED" => Some(Self::Cancelled),
            "TASK_STATUS_TIMEOUT" => Some(Self::Timeout),
            "TASK_STATUS_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod orchestrator_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct OrchestratorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OrchestratorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OrchestratorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OrchestratorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OrchestratorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn submit_task(
            &mut self,
            request: impl tonic::IntoRequest<super::SubmitTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SubmitTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/SubmitTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "SubmitTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_task_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTaskStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTaskStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/GetTaskStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "GetTaskStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_task(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/CancelTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "CancelTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_tasks(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTasksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTasksResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ListTasks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ListTasks",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_session_context(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSessionContextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionContextResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/GetSessionContext",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "GetSessionContext",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Template catalog
        pub async fn list_templates(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTemplatesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTemplatesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ListTemplates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ListTemplates",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Human intervention endpoints
        pub async fn approve_task(
            &mut self,
            request: impl tonic::IntoRequest<super::ApproveTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApproveTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ApproveTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ApproveTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_pending_approvals(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPendingApprovalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPendingApprovalsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/GetPendingApprovals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "GetPendingApprovals",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Workflow control (pause/resume/cancel)
        pub async fn pause_task(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PauseTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/PauseTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "PauseTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn resume_task(
            &mut self,
            request: impl tonic::IntoRequest<super::ResumeTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResumeTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ResumeTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ResumeTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_control_state(
            &mut self,
            request: impl tonic::IntoRequest<super::GetControlStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetControlStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/GetControlState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "GetControlState",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Schedule management
        pub async fn create_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/CreateSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "CreateSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::GetScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/GetSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "GetSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_schedules(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSchedulesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSchedulesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ListSchedules",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ListSchedules",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/UpdateSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "UpdateSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/DeleteSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "DeleteSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn pause_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PauseScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/PauseSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "PauseSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn resume_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::ResumeScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResumeScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.OrchestratorService/ResumeSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.OrchestratorService",
                        "ResumeSchedule",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamRequest {
    #[prost(string, tag = "1")]
    pub workflow_id: ::prost::alloc::string::String,
    /// optional filter by event types
    #[prost(string, repeated, tag = "2")]
    pub types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// resume from this event id (exclusive) - backward compat
    #[prost(uint64, tag = "3")]
    pub last_event_id: u64,
    /// resume from this Redis stream ID (preferred)
    #[prost(string, tag = "4")]
    pub last_stream_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskUpdate {
    #[prost(string, tag = "1")]
    pub workflow_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// backward compat
    #[prost(uint64, tag = "6")]
    pub seq: u64,
    /// Redis stream ID for robust resume
    #[prost(string, tag = "7")]
    pub stream_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod streaming_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct StreamingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StreamingServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StreamingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StreamingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StreamingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn stream_task_execution(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TaskUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/shannon.orchestrator.StreamingService/StreamTaskExecution",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "shannon.orchestrator.StreamingService",
                        "StreamTaskExecution",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
