// This file is @generated by prost-build.
/// Task metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskMetadata {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(map = "string, string", tag = "6")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Max concurrent agents (default: 5)
    #[prost(int32, tag = "7")]
    pub max_agents: i32,
    /// Token budget for this task
    #[prost(double, tag = "8")]
    pub token_budget: f64,
}
/// Token usage tracking
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenUsage {
    #[prost(int32, tag = "1")]
    pub prompt_tokens: i32,
    #[prost(int32, tag = "2")]
    pub completion_tokens: i32,
    #[prost(int32, tag = "3")]
    pub total_tokens: i32,
    #[prost(double, tag = "4")]
    pub cost_usd: f64,
    #[prost(string, tag = "5")]
    pub model: ::prost::alloc::string::String,
    #[prost(enumeration = "ModelTier", tag = "6")]
    pub tier: i32,
    /// Provider that served the request (e.g., openai, anthropic, google, groq, xai, ollama)
    #[prost(string, tag = "7")]
    pub provider: ::prost::alloc::string::String,
}
/// Execution metrics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionMetrics {
    #[prost(int64, tag = "1")]
    pub latency_ms: i64,
    #[prost(message, optional, tag = "2")]
    pub token_usage: ::core::option::Option<TokenUsage>,
    #[prost(bool, tag = "3")]
    pub cache_hit: bool,
    #[prost(double, tag = "4")]
    pub cache_score: f64,
    #[prost(int32, tag = "5")]
    pub agents_used: i32,
    #[prost(enumeration = "ExecutionMode", tag = "6")]
    pub mode: i32,
}
/// Tool call representation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolCall {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub parameters: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, tag = "3")]
    pub tool_id: ::prost::alloc::string::String,
}
/// Tool result
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolResult {
    #[prost(string, tag = "1")]
    pub tool_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub output: ::core::option::Option<::prost_types::Value>,
    #[prost(enumeration = "StatusCode", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub execution_time_ms: i64,
}
/// Common status codes for Shannon platform
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StatusCode {
    Unspecified = 0,
    Ok = 1,
    Error = 2,
    Timeout = 3,
    RateLimited = 4,
    BudgetExceeded = 5,
}
impl StatusCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_CODE_UNSPECIFIED",
            Self::Ok => "STATUS_CODE_OK",
            Self::Error => "STATUS_CODE_ERROR",
            Self::Timeout => "STATUS_CODE_TIMEOUT",
            Self::RateLimited => "STATUS_CODE_RATE_LIMITED",
            Self::BudgetExceeded => "STATUS_CODE_BUDGET_EXCEEDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "STATUS_CODE_OK" => Some(Self::Ok),
            "STATUS_CODE_ERROR" => Some(Self::Error),
            "STATUS_CODE_TIMEOUT" => Some(Self::Timeout),
            "STATUS_CODE_RATE_LIMITED" => Some(Self::RateLimited),
            "STATUS_CODE_BUDGET_EXCEEDED" => Some(Self::BudgetExceeded),
            _ => None,
        }
    }
}
/// Execution mode for agent tasks
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionMode {
    Unspecified = 0,
    /// Direct tool/cache response
    Simple = 1,
    /// Single agent with LLM
    Standard = 2,
    /// Multi-agent DAG execution
    Complex = 3,
}
impl ExecutionMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_MODE_UNSPECIFIED",
            Self::Simple => "EXECUTION_MODE_SIMPLE",
            Self::Standard => "EXECUTION_MODE_STANDARD",
            Self::Complex => "EXECUTION_MODE_COMPLEX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_MODE_SIMPLE" => Some(Self::Simple),
            "EXECUTION_MODE_STANDARD" => Some(Self::Standard),
            "EXECUTION_MODE_COMPLEX" => Some(Self::Complex),
            _ => None,
        }
    }
}
/// Model tier for LLM selection
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelTier {
    Unspecified = 0,
    /// GPT-5-nano, Haiku, etc. (target: 50% - not enforced)
    Small = 1,
    /// GPT-5, Sonnet, etc. (target: 40% - not enforced)
    Medium = 2,
    /// GPT-5-thinking, Opus, etc. (target: 10% - not enforced)
    Large = 3,
}
impl ModelTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODEL_TIER_UNSPECIFIED",
            Self::Small => "MODEL_TIER_SMALL",
            Self::Medium => "MODEL_TIER_MEDIUM",
            Self::Large => "MODEL_TIER_LARGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_TIER_SMALL" => Some(Self::Small),
            "MODEL_TIER_MEDIUM" => Some(Self::Medium),
            "MODEL_TIER_LARGE" => Some(Self::Large),
            _ => None,
        }
    }
}
/// Cognitive strategy for intelligent task routing
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CognitiveStrategy {
    CognitiveUnspecified = 0,
    /// Simple direct execution
    CognitiveDirect = 1,
    /// Current DAG decomposition
    CognitiveDecompose = 2,
    /// Iterative discovery with hypothesis testing
    CognitiveExploratory = 3,
    /// Reason-Act-Observe loops for debugging
    CognitiveReact = 4,
    /// Deep investigation with citations
    CognitiveResearch = 5,
    /// Formal hypothesis testing with belief tracking
    CognitiveScientific = 6,
}
impl CognitiveStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CognitiveUnspecified => "COGNITIVE_UNSPECIFIED",
            Self::CognitiveDirect => "COGNITIVE_DIRECT",
            Self::CognitiveDecompose => "COGNITIVE_DECOMPOSE",
            Self::CognitiveExploratory => "COGNITIVE_EXPLORATORY",
            Self::CognitiveReact => "COGNITIVE_REACT",
            Self::CognitiveResearch => "COGNITIVE_RESEARCH",
            Self::CognitiveScientific => "COGNITIVE_SCIENTIFIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COGNITIVE_UNSPECIFIED" => Some(Self::CognitiveUnspecified),
            "COGNITIVE_DIRECT" => Some(Self::CognitiveDirect),
            "COGNITIVE_DECOMPOSE" => Some(Self::CognitiveDecompose),
            "COGNITIVE_EXPLORATORY" => Some(Self::CognitiveExploratory),
            "COGNITIVE_REACT" => Some(Self::CognitiveReact),
            "COGNITIVE_RESEARCH" => Some(Self::CognitiveResearch),
            "COGNITIVE_SCIENTIFIC" => Some(Self::CognitiveScientific),
            _ => None,
        }
    }
}
