# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from llm import llm_pb2 as llm_dot_llm__pb2


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCompletion = channel.unary_unary(
                '/shannon.llm.LLMService/GenerateCompletion',
                request_serializer=llm_dot_llm__pb2.GenerateCompletionRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.GenerateCompletionResponse.FromString,
                _registered_method=True)
        self.StreamCompletion = channel.unary_stream(
                '/shannon.llm.LLMService/StreamCompletion',
                request_serializer=llm_dot_llm__pb2.GenerateCompletionRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.CompletionChunk.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/shannon.llm.LLMService/EmbedText',
                request_serializer=llm_dot_llm__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.EmbedTextResponse.FromString,
                _registered_method=True)
        self.AnalyzeComplexity = channel.unary_unary(
                '/shannon.llm.LLMService/AnalyzeComplexity',
                request_serializer=llm_dot_llm__pb2.AnalyzeComplexityRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.AnalyzeComplexityResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/shannon.llm.LLMService/ListModels',
                request_serializer=llm_dot_llm__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.ListModelsResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeComplexity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompletion,
                    request_deserializer=llm_dot_llm__pb2.GenerateCompletionRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.GenerateCompletionResponse.SerializeToString,
            ),
            'StreamCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCompletion,
                    request_deserializer=llm_dot_llm__pb2.GenerateCompletionRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.CompletionChunk.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=llm_dot_llm__pb2.EmbedTextRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.EmbedTextResponse.SerializeToString,
            ),
            'AnalyzeComplexity': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeComplexity,
                    request_deserializer=llm_dot_llm__pb2.AnalyzeComplexityRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.AnalyzeComplexityResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=llm_dot_llm__pb2.ListModelsRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shannon.llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shannon.llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.llm.LLMService/GenerateCompletion',
            llm_dot_llm__pb2.GenerateCompletionRequest.SerializeToString,
            llm_dot_llm__pb2.GenerateCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shannon.llm.LLMService/StreamCompletion',
            llm_dot_llm__pb2.GenerateCompletionRequest.SerializeToString,
            llm_dot_llm__pb2.CompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.llm.LLMService/EmbedText',
            llm_dot_llm__pb2.EmbedTextRequest.SerializeToString,
            llm_dot_llm__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeComplexity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.llm.LLMService/AnalyzeComplexity',
            llm_dot_llm__pb2.AnalyzeComplexityRequest.SerializeToString,
            llm_dot_llm__pb2.AnalyzeComplexityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shannon.llm.LLMService/ListModels',
            llm_dot_llm__pb2.ListModelsRequest.SerializeToString,
            llm_dot_llm__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
